---
# defaults file for ASM-Role

provider:
  server: "{{ ansible_host }}"
  user: "{{ ansible_user }}"
  password: "{{ ansible_ssh_pass }}"
  server_port: "{{ F5_Admin_Port }}"
  validate_certs: "no"

