---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: Say Hello
      condition: event.payload.message == "Ansible Please Block Some IPs"

      action:
        set_fact:
          test_payload: "{{ event.payload.payload }}"
        run_playbook:
          name: f5-playbooks/block-ips-playbook/block-ips.yaml
          var_root: test_payload
