---
# Modify based on deployment
ansible_python_interpreter: "{{ ansible_playbook_python }}" 

#Use-Case Variables
F5_VIP_Name: VS_WEB
F5_VIP_Port: "80"
F5_Admin_Port: "443"
ASM_Policy_Name: "WAF-POLICY"
ASM_Policy_File: "/tmp/f5/WAF-POLICY.xml"
Block_My_IP: "yes"