---
- hosts: lb
  connection: local
  gather_facts: true
  vars_files:
    - vars/f5_vars.yml
  vars:
    Blocked_IPs: "{{ event.payload.payload }}"
  roles:
    - "{{playbook_dir}}/roles/debugging"
    # - block_my_ip
    # - waf_export_policy
    # - waf_block_ip
    # - waf_import_apply_policy

